org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC -XX:ReservedCodeCacheSize=256m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
kapt.incremental.apt=false
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36,35,34,33,31
org.gradle.java.home=C:\\Users\\mdsak\\.jdk\\jdk-17.0.14+7
