// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDimWawlIzL_E-mtibgg3U8Iorenw1wEiI',
    appId: '1:1006655599669:web:43ff8cc5e643ba1aed2d7c',
    messagingSenderId: '1006655599669',
    projectId: 'messfinder-efd6f',
    authDomain: 'messfinder-efd6f.firebaseapp.com',
    storageBucket: 'messfinder-efd6f.firebasestorage.app',
    measurementId: 'G-0D38RK305R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9hOOD7yGW0g140Ni3nTsawzj3Q4UiIk',
    appId: '1:1006655599669:android:bf7b1884290fd292ed2d7c',
    messagingSenderId: '1006655599669',
    projectId: 'messfinder-efd6f',
    storageBucket: 'messfinder-efd6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqlfmjl8KpBKgc0AlYPW0qmtrSlCppRU',
    appId: '1:1006655599669:ios:828692f60bf886f3ed2d7c',
    messagingSenderId: '1006655599669',
    projectId: 'messfinder-efd6f',
    storageBucket: 'messfinder-efd6f.firebasestorage.app',
    iosBundleId: 'com.example.messFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqlfmjl8KpBKgc0AlYPW0qmtrSlCppRU',
    appId: '1:1006655599669:ios:828692f60bf886f3ed2d7c',
    messagingSenderId: '1006655599669',
    projectId: 'messfinder-efd6f',
    storageBucket: 'messfinder-efd6f.firebasestorage.app',
    iosBundleId: 'com.example.messFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDimWawlIzL_E-mtibgg3U8Iorenw1wEiI',
    appId: '1:1006655599669:web:2dc91f3ee878fc5ded2d7c',
    messagingSenderId: '1006655599669',
    projectId: 'messfinder-efd6f',
    authDomain: 'messfinder-efd6f.firebaseapp.com',
    storageBucket: 'messfinder-efd6f.firebasestorage.app',
    measurementId: 'G-3NGN128Z3C',
  );
}
